name: attend_easee
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_database: ^11.2.0
  intl: ^0.19.0
  month_year_picker: ^0.4.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.9.0
  flutter_test:
    sdk: flutter
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  curved_navigation_bar: ^1.0.3
  slide_to_act: ^2.0.2
  flutter_lints: ^5.0.0
  geocoding: ^3.0.0
  location: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Logo.json
    - assets/lock.svg
    - assets/office.svg
    - assets/Profile.json
    - assets/Home.json
    - assets/History.json
    - assets/Successful.json
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
